// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQetLMovM9QkeUMYrU1KAfYaWZlY3fiE',
    appId: '1:896785027723:web:c5cb6d77b70a09599e7a8e',
    messagingSenderId: '896785027723',
    projectId: 'zwift-34e94',
    authDomain: 'zwift-34e94.firebaseapp.com',
    storageBucket: 'zwift-34e94.appspot.com',
    measurementId: 'G-5V87HMF31T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuIq5H7TljQudh9QWDAd6gyr9ZnBvjBgg',
    appId: '1:896785027723:android:c290047fd389da7b9e7a8e',
    messagingSenderId: '896785027723',
    projectId: 'zwift-34e94',
    storageBucket: 'zwift-34e94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTQ77laitnfmr8WLr5vPbH2TSglMS42NY',
    appId: '1:896785027723:ios:77240e3bd24a85d49e7a8e',
    messagingSenderId: '896785027723',
    projectId: 'zwift-34e94',
    storageBucket: 'zwift-34e94.appspot.com',
    androidClientId: '896785027723-tnrv6hmd0ki58rffmajkurs6be1r3n77.apps.googleusercontent.com',
    iosClientId: '896785027723-p9cj4gv125dbn68pc3p7ja1mhf3uhkdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
